// To add a character image: drop the file into public/characters/ and set
// image: "/characters/filename.jpg"  (or .png/.webp). Leave null for placeholder.
export const CHARACTERS = [
  {
    id: 1,
    name: "Guts",
    title: "The Black Swordsman",
    faction: "Branded",
    race: "Human",
    status: "Alive",
    archetype: "Protagonist",
    sym: "†",
    symColor: "#cc2020",
    gradFrom: "#080000",
    gradTo: "#200808",
    factionColor: "#cc2020",
    image: "/characters/guts.png",
    wiki: "https://berserk.fandom.com/wiki/Guts",
    abilities: ["Berserker Armor", "Dragonslayer", "Iron Will"],
    desc: "Born from a corpse and branded as a sacrifice, Guts wages an unending war against the apostles of the God Hand—armed with a sword no ordinary man could lift and a will that refuses to break.",
  },
  {
    id: 2,
    name: "Griffith",
    title: "The White Hawk / Femto",
    faction: "God Hand",
    race: "Reincarnated",
    status: "God Hand",
    archetype: "Antagonist",
    sym: "◆",
    symColor: "#2a7fd4",
    gradFrom: "#0a1a38",
    gradTo: "#183060",
    factionColor: "#60aaee",
    image: "/characters/griffith.png",
    wiki: "https://berserk.fandom.com/wiki/Griffith",
    abilities: ["Beherit", "Divine Causality", "Moonlight Boy"],
    desc: "Once humanity's most brilliant commander, Griffith sacrificed his comrades during the Eclipse to be reborn as Femto—the fifth of the God Hand and a wielder of fate itself.",
  },
  {
    id: 3,
    name: "Casca",
    title: "The Fierce Female Warrior",
    faction: "Branded",
    race: "Human",
    status: "Alive",
    archetype: "Warrior",
    sym: "◈",
    symColor: "#a04080",
    gradFrom: "#180610",
    gradTo: "#280a1c",
    factionColor: "#c05090",
    image: "/characters/casca.png",
    wiki: "https://berserk.fandom.com/wiki/Casca",
    abilities: ["Elite Swordsmanship", "Band Commander", "Unyielding Spirit"],
    desc: "The only female warrior of the Band of the Hawk and among its finest fighters. Her fate during the Eclipse became the wound that drives Guts across the astral world.",
  },
  {
    id: 4,
    name: "Skull Knight",
    title: "The King of Interstice",
    faction: "Unknown",
    race: "Undead",
    status: "Unknown",
    archetype: "Enigma",
    sym: "⊕",
    symColor: "#50a0a8",
    gradFrom: "#040c0e",
    gradTo: "#0c1e20",
    factionColor: "#60b8c0",
    image: "/characters/skull_knight.png",
    wiki: "https://berserk.fandom.com/wiki/Skull_Knight",
    abilities: ["Sword of Actuation", "Beherit Sword", "Astral Travel"],
    desc: "Ancient beyond memory, the Skull Knight rides between worlds as a spectral sentinel. His centuries-long war with the God Hand makes him one of the few beings they fear.",
  },
  {
    id: 5,
    name: "Zodd",
    title: "The Immortal",
    faction: "Apostle",
    race: "Apostle",
    status: "Alive",
    archetype: "Apostle",
    sym: "◉",
    symColor: "#c01818",
    gradFrom: "#0e0000",
    gradTo: "#1e0404",
    factionColor: "#c01818",
    image: "/characters/zodd.png",
    wiki: "https://berserk.fandom.com/wiki/Zodd",
    abilities: ["Apostle Transformation", "Immortal Body", "Sword Mastery"],
    desc: "A legendary warrior who has slaughtered armies for centuries. Zodd lives only for battle and respects only those who can match him—a list on which Guts' name now appears.",
  },
  {
    id: 6,
    name: "Puck",
    title: "The Elf of Elfhelm",
    faction: "Companions",
    race: "Elf",
    status: "Alive",
    archetype: "Support",
    sym: "✧",
    symColor: "#28b850",
    gradFrom: "#020e06",
    gradTo: "#081a0e",
    factionColor: "#38c860",
    image: "/characters/puck.jpg",
    wiki: "https://berserk.fandom.com/wiki/Puck",
    abilities: ["Healing Dust", "Empathy Sensing", "Boundless Resilience"],
    desc: "A mischievous wind elf with potent healing powers and a genuine heart. Puck serves as Guts' first companion—equal parts conscience, comic relief, and lifeline on his dark road.",
  },
  {
    id: 7,
    name: "Farnese",
    title: "Holy Iron Chain Knight",
    faction: "Holy See",
    race: "Human",
    status: "Alive",
    archetype: "Knight",
    sym: "✝",
    symColor: "#c89820",
    gradFrom: "#100c00",
    gradTo: "#201800",
    factionColor: "#d8aa30",
    image: "/characters/farnese.jpg",
    wiki: "https://berserk.fandom.com/wiki/Farnese_de_Vandimion",
    abilities: ["Magical Aptitude", "Fire Control", "Noble Authority"],
    desc: "Born into nobility and drawn compulsively to fire, Farnese walked the painful road from fanatical Holy See commander to student of the witch Flora—humbled by the truth of the supernatural world.",
  },
  {
    id: 8,
    name: "Serpico",
    title: "Wind Swordsman",
    faction: "Holy See",
    race: "Human",
    status: "Alive",
    archetype: "Duelist",
    sym: "≋",
    symColor: "#30a0d8",
    gradFrom: "#040c18",
    gradTo: "#0a1828",
    factionColor: "#48b8f0",
    image: "/characters/serpico.jpg",
    wiki: "https://berserk.fandom.com/wiki/Serpico",
    abilities: ["Sylph Cloak", "Sylph Sword", "Tactical Mastery"],
    desc: "A noble bastard who pledged his existence to Farnese's protection. Armed with wind sylph equipment, Serpico fights with cold efficiency born from a lifetime of calculated restraint.",
  },
  {
    id: 9,
    name: "Schierke",
    title: "The Young Witch",
    faction: "Magic Users",
    race: "Human",
    status: "Alive",
    archetype: "Mage",
    sym: "⊛",
    symColor: "#208858",
    gradFrom: "#020e08",
    gradTo: "#081a10",
    factionColor: "#30a868",
    image: "/characters/schierke.jpg",
    wiki: "https://berserk.fandom.com/wiki/Schierke",
    abilities: ["Od Manipulation", "Rainstorm", "Berserker Armor Control"],
    desc: "Trained in the deep forest by the great witch Flora, Schierke's mastery of Od makes her Guts' most vital companion—especially when the Berserker Armor threatens to consume his mind.",
  },
  {
    id: 10,
    name: "Isidro",
    title: "Aspiring Swordsman",
    faction: "Companions",
    race: "Human",
    status: "Alive",
    archetype: "Rogue",
    sym: "◇",
    symColor: "#d06020",
    gradFrom: "#100600",
    gradTo: "#201000",
    factionColor: "#e07830",
    image: "/characters/isidro.png",
    wiki: "https://berserk.fandom.com/wiki/Isidro",
    abilities: ["Fire Bombs", "Agility", "Salamander Dagger"],
    desc: "A street thief who latched onto Guts dreaming of swordsmanship fame. What he lacks in skill he compensates for with cunning, speed, and an inexhaustible supply of explosive fire tricks.",
  },
  {
    id: 11,
    name: "Rickert",
    title: "The Young Blacksmith",
    faction: "Band of the Hawk",
    race: "Human",
    status: "Alive",
    archetype: "Inventor",
    sym: "⚙",
    symColor: "#708830",
    gradFrom: "#080c00",
    gradTo: "#141800",
    factionColor: "#88a040",
    image: "/characters/rickert.png",
    wiki: "https://berserk.fandom.com/wiki/Rickert",
    abilities: ["Mechanical Engineering", "Cannon Arm", "Tactical Mind"],
    desc: "The youngest member of the original Band of the Hawk who survived the Eclipse by chance. Rickert channeled grief into craftsmanship, forging mechanical weapons and eventually defying Griffith to his face.",
  },
  {
    id: 12,
    name: "Void",
    title: "The Idea of Evil",
    faction: "God Hand",
    race: "Demon God",
    status: "God Hand",
    archetype: "God Hand",
    sym: "○",
    symColor: "#7820c0",
    gradFrom: "#060010",
    gradTo: "#100018",
    factionColor: "#9030e0",
    image: "/characters/void.png",
    wiki: "https://berserk.fandom.com/wiki/Void",
    abilities: ["Causality Manipulation", "Sacrificial Rite", "Astral Dominion"],
    desc: "The eldest and most inscrutable of the God Hand. Void presides over the Eclipse with cold omniscience, manipulating causality itself—his face a brain laid bare where features should be.",
  },
];

export const STATUS_STYLE = {
  Alive: { dot: "#4a8a4a", text: "#6aaa6a" },
  Deceased: { dot: "#5a5a7a", text: "#7a7a9a" },
  "God Hand": { dot: "#c5a028", text: "#d4b040" },
  Unknown: { dot: "#4a5a6a", text: "#6a7a8a" },
};